### ISSUE TITLE
Ubuntu error

### ISSUE THREAD

**Issue by softy2k** [Risk3sixty-Labs/facereplace#4]
Hello

**1**. I try to install to Ubuntu (from Amazon AWS), but I receive multiple errors :

sudo npm install -g facereplace
```
> npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
> npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
> npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
> npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
> /usr/bin/facereplace -> /usr/lib/node_modules/facereplace/dist/bin/facereplace
> 
> > @tensorflow/tfjs-node@1.7.4 install /usr/lib/node_modules/facereplace/node_modules/@tensorflow/tfjs-node
> > node scripts/install.js
> 
> CPU-linux-1.7.4.tar.gz
> (node:1942) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/facereplace/node_modules/@tensorflow/tfjs-node/deps'
> (node:1942) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:1942) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> 
> > canvas@2.6.1 install /usr/lib/node_modules/facereplace/node_modules/canvas
> > node-pre-gyp install --fallback-to-build
> 
> node-pre-gyp WARN Using request for node-pre-gyp https download
> node-pre-gyp WARN Pre-built binaries not installable for canvas@2.6.1 and node@12.18.0 (node-v72 ABI, glibc) (falling back to source compile with node-gyp)
> node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/usr/lib/node_modules/facereplace/node_modules/canvas/build'
> gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/home/ubuntu/.cache/node-gyp/12.18.0"
> gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/facereplace/node_modules/canvas/.node-gyp"
> gyp WARN install got an error, rolling back install
> gyp WARN install got an error, rolling back install
> gyp ERR! configure error
> gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/facereplace/node_modules/canvas/.node-gyp'
> gyp ERR! System Linux 5.3.0-1023-aws
> gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/lib/node_modules/facereplace/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/usr/lib/node_modules/facereplace/node_modules/canvas/build/Release" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
> gyp ERR! cwd /usr/lib/node_modules/facereplace/node_modules/canvas
> gyp ERR! node -v v12.18.0
> gyp ERR! node-gyp -v v5.1.0
> gyp ERR! not ok
> node-pre-gyp ERR! build error
> node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/lib/node_modules/facereplace/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/usr/lib/node_modules/facereplace/node_modules/canvas/build/Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
> node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/facereplace/node_modules/canvas/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
> node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
> node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
> node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
> node-pre-gyp ERR! System Linux 5.3.0-1023-aws
> node-pre-gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/facereplace/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
> node-pre-gyp ERR! cwd /usr/lib/node_modules/facereplace/node_modules/canvas
> node-pre-gyp ERR! node -v v12.18.0
> node-pre-gyp ERR! node-pre-gyp -v v0.11.0
> node-pre-gyp ERR! not ok
> Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/lib/node_modules/facereplace/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/usr/lib/node_modules/facereplace/node_modules/canvas/build/Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/facereplace/node_modules/chokidar/node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"12.18.0","npm":"6.14.4"})
> npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/facereplace/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! canvas@2.6.1 install: `node-pre-gyp install --fallback-to-build`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the canvas@2.6.1 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 

```

**2**. No succes in Windows 7 and 10

**Comment by whatl3y** [comment]
The errors provided are `EACCESS` writing to the file system in `usr/libs/node_modules/...`, which are not related to this package but to how `npm` is installed on the machine. You should not need to use `sudo` to install if node/npm is installed correctly.

I just stood up a blank AWS Ubuntu LTS version, installed node/npm via [nvm](https://github.com/nvm-sh/nvm), and installed facereplace (`npm install -g facereplace`) without issue. I recommend trying to use `nvm` to install node and trying again.
